services:

  app:
    image: ivanmmf/java-study-part-5:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Java_Study_Part_5

  db:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: Java_Study_Part_5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 379159
